# Gradient Boosting
This presentation was prepared by Violet LaCasse.

## Introduction

This presentation will:

* Define Gradient Boosting (and boosting)

* Provide examples of Gradient Boosting in regression and Gradient Boosting in classification

* Discuss the advantages and disadvantages of Gradient Boosting


## What is Boosting?

**Boosting**: an iterative *ensemble learning* technique that takes multiple weaker predictive models to create a single stronger model

* **Ensemble learning**: combining multiple models to create a new (better) one

* Models are also referred to as "learners"

    + A "weak learner" is only slightly better than random guessing

Boosting improves predictive accuracy by **having each new model correct the mistakes of the previous one** through varying methods.

### Major Steps in (Adaptive) Boosting:

1. **Selecting initial weights**

Here, we're looking at Adaptive Boosting, which uses weights as a corrective measure.

All data points in the training set are given equal initial weights.

2. **Sequential training**

The first model is trained using the previously weighted data. The performance of this model is usually weak (a "weak learner").

So, we take the data points that the model didn't handle well and give them higher weights than points that were identified correctly, assigning them more importance in the next model.

3. **Iterating**

Having addressed the mistakes from the previous model, this next model's performance is evaluated. Misclassified data points have their weights increased.

This process is **repeated multiple times** until there is an **ensemble of weak models** with varying predictive accuracies.

4. **Aggregating**

The predictions of all the weak models in the ensemble are aggregated to **create a final predictive model**.

Models that have higher predictive accuracy relative to the others in the ensemble have more influence on the final model.

Finally, the resulting model can be used with the test set to evaluate the model's overall performance.

Boosting can be contrasted with Bagging (see Random Forests).

## What is Gradient Boosting?

**Gradient Boosting**: a type of boosting that relies on *residuals* to minimize the *loss function* through *descent*

* **Loss function**: a measure of how good or bad a model is at predicting a value compared to the actual value

    + Commonly MSE (mean squared error) for regression

    + Commonly cross-entropy aka log loss (difference between predicted probability distribution and actual probability distribution) for classification

    + Smaller loss means more accurate predictions

* **Gradient descent**: an optimization algorithm that minimizes the loss function (prediction error)

    + Typically minimizes loss by changing parameters (weight/bias), but this is not the case in Gradient Boosting

    + **(Negative) Gradient**: the slope of the loss function that tells the algorithm which *direction* to "step" to minimize the loss function

        - Determined by pseudo-residuals in Gradient Boosting
    
    + **Learning rate**: dictates the *size* of each iterative "step" the algorithm takes to minimize the loss function

        - Too small: waste of computational resources
        
        - Too big: might miss the minimum of the function entirely

        - Also used to prevent overfitting

### Major Steps in Gradient Boosting:

1. **Creating an initial prediction**

Using a training set, we create a model where the **initial prediction** of the target variable for all data points is a constant, so:

$$
F_{0}(x) = \bar{y}
$$

Usually, the models used for Gradient Boosting are decision trees because they're fairly versatile.

2. **Calculating (pseudo-) residuals**

Then, we **calculate the residuals** (or **pseudo-residuals** as they're referred to in gradient boosting) for each data point in the dataset. *When using MSE as the loss function*, the pseudo-residual is:

$$
r_{im} = y_{i} - F_{m-1}(x_{i})
$$

or
$$
r_{im} = y_{i} - \hat{y}_{i} (actual - predicted)
$$

where:

* i = 1, ..., n (n is the number of observations in the sample)

* m = 1, ..., M (M is the total number of iterations/models)

So for this first iteration/model, because the predicted value is $\bar{y}$:

$$
r_{i1} = y_{i} - \bar{y}
$$

3. **Creating a new model (and shrinkage)**

Gradient Boosting minimizes the loss function by sequentially having each new model **fix the errors** of the previous model. So, the **pseudo-residuals of the previous model become the target variable**. The features stay the same.

Over time, as the models get better at predicting the pseudo-residuals, error decreases, because we are "following" the pseudo-residuals (also referred to as the **negative gradient** for this reason) down the loss function.

This is how each new model learns to fix the errors of the previous model and how the loss function gets minimized.

Gradient Boosting is prone to overfitting. To help combat this, before adding a model to the ensemble, the model's predictions are scaled according to the learning rate (a process called **shrinkage**). This process weights each model's contribution to the final prediction.

4. **Iterating**

This process is repeated and continues until we want it to stop (i.e. after a certain number of iterations, or until loss stops decreasing).

5. **Aggregating**

Ultimately, the predictions of all models in the ensemble are combined. This is what the final prediction of the initial target variable looks like:

$$
y_{pred} = F_{0}(x) + \eta \times r_{1} + \eta \times r_{2} + ... + \eta \times r_{n}
$$

where:

* $\eta$ is the learning rate

* $r_{n}$ is the residuals of the nth model (tree, if you're using decision trees).

## Gradient Boosting: Regression

Both functions for Gradient Boosting Regression and Classification can be found in the sklearn library.

For an example of Gradient Boosting in regression, we will be using the sklearn California housing dataset.

```{python}
import sklearn
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing(as_frame = True)
```

Basic info about the dataset:

```{python}
housing.frame.head()
```

```{python}
housing.frame.shape
```

```{python}
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

X = housing.data
y = housing.target # MedHouseVal

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state = 3255)
```

```{python}
gb_reg = GradientBoostingRegressor(loss = 'squared_error',
    learning_rate = 0.1, # "step size"
    n_estimators = 400, # number of iterations/models (trees in this case)
    max_depth = 5,
    random_state = 3255,
    n_iter_no_change = 50)

gb_reg.fit(train_X, train_y)
```

```{python}
pred_y = gb_reg.predict(test_X)

mse_reg = mean_squared_error(test_y, pred_y)
r2_reg = r2_score(test_y, pred_y)

print(f'R2: {r2_reg:.2f}')
print(f'RMSE: {(mse_reg ** (1/2)):.2f}')
```

R-squared (amount of variation in `MedHouseVal` explained by the features) is decent, and given the context of the problem and the values of the target variable, the RMSE isn't so bad either.

**To see improvement**, you may want to try the `GridSearchCV` function in order to find which combinations of hyperparameters yield the best results (however this is very computationally expensive).

## Gradient Boosting in Classification

For an example of Gradient Boosting in regression, we will be using the sklearn Wisconsin breast cancer dataset.

```{python}
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer(as_frame = True)
```

```{python}
cancer.frame.head()
```

```{python}
cancer.frame.shape
```

```{python}
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

X = cancer.data
y = cancer.target

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state = 3255)
```

```{python}
gb_clf = GradientBoostingClassifier(loss = 'log_loss',
    learning_rate = 0.1, # "step size"
    n_estimators = 400, # number of iterations/models (trees in this case)
    max_depth = 5,
    random_state = 3255,
    n_iter_no_change = 50)

gb_clf.fit(train_X, train_y)
```

```{python}
pred_y = gb_clf.predict(test_X)

gb_acc = accuracy_score(test_y, pred_y)

print(f'Accuracy score: {gb_acc}')
```

The accuracy score is fairly high, so we can say that this Gradient Boosting model is quite good at predicting whether a patient has breast cancer or not with the given features.

## Advantages and Disadvantages

###### Advantages:

* Good for both regression and classification

* Good with large/imbalanced data

* Typically very good predictive accuracy

###### Disadvantages:

* Prone to overfitting with too many boosting rounds

    + This is why tuning hyperparameters is important

* Can be very computationally expensive

## Conclusion

**ESSENTIALLY**, Gradient Boosting is an algorithm that uses residuals to minimize overall error by sequentially fixing previous errors. With the right tuning, it can be a very powerful predictive tool.

## References

https://www.geeksforgeeks.org/machine-learning/boosting-in-machine-learning/ 

https://www.geeksforgeeks.org/machine-learning/ml-gradient-boosting/ 

https://www.datacamp.com/tutorial/guide-to-the-gradient-boosting-algorithm 

https://apxml.com/courses/getting-started-with-gradient-boosting-algorithms/chapter-2-the-gradient-boosting-machine/gbm-algorithm-steps