---
title: "Homework Assignment 2"
author: "Mallory Whitlow"
toc: true
number-sections: true
highlight-style: pygments
format: 
  html: 
    code-fold: false
    html-math-method: katex
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm

##  docx: Never, unless to accommodate a collaborator
---

## 6.2.1 Part 1. Contributing to Class Notes

This section contains a guide on how to contribute to the class note repository.

### Create a fork of the notes repository

Creating a fork is essentially the same thing as copying a repository. We need to copy the repository so that the changes we make do not conflict with the original code.

1.  In HuskyCT, click the "Homework Descriptions" link, which will take you to the `Homework` section in the class notes.
2.  Go to the section called `Preliminaries` , then click the <https://github.com/statds/ids-s26> link to be taken to the Intro to Data Science Spring 2026 class notes on Github.
3.  In the `code` tab, the fork button is on the top right corner of the screen. Click **Fork**-\> **Create Fork**
4.  Once clicking **Fork**, you should arrive on a screen with the forked class notes repository.

### Clone forked repository to computer

Use the following code in the terminal to clone the forked repository to your computer. Make sure to replace Github_Username with your Github username.

```{bash}
cd ~/Documents/Github
```

I cloned the repository into the Github folder on my computer, so either replace "Github" with the folder you would like to clone to or skip this part and use the code below to clone.

```{bash}
git clone https://github.com/Github_Username/ids-s26.git
```

```{bash}
cd ids-s26
```

### Render the class notes 

First, we are going to create a virtual environment to work with this repository.

```{bash}
python -m venv hw2
```

```{bash}
source hw2/bin/activate 
```

These commands create and open a folder within the class notes that runs the Python built-in virtual environment module. This gives us a clean environment so that we do not have to install packages globally and potentially mess with other coding projects.

```{bash}
pip install -r requirements.txt
```

This installs the required packages from the class notes.

```{bash}
quarto render
```

```{bash}
quarto preview
```

I was able to render all of the class notes, though it took a while to load.

At this point, I wanted to commit this homework into my repository. To do that, I must first clone the homework 2 repository to my local machine. I used this line below:

```{bash}
git clone git@github.com:ds-uconn/homework-2-mallorywhitlow.git
```

After the repository was cloned, I then added the homework file, hw2.qmd, into the cloned repository directory.

```{bash}
git add .
```

Once it was added, I committed the changes to be pushed.

```{bash}
git commit -m "Adding hw2.qmd to the homework 2 repository"
```

### Making New Branch

To experiment with changes needed for my wishes on the class notes, I needed to first create a new branch so that I don't commit any changes that I don't want to save later. This is helpfull so I don't commit to any cahnges until I kno what I want. This branch was created off of main in the IDS-s26 repo.

```{bash}
git checkout -b "mall-exp"
```

To make sure I was in the right branch I used this command:

```{bash}
git branch
```

It wil have a star next to the name of the branch you are already in. In my case, the star was on "mall-exp" so I was all set. If it isn't, you can use this command to switch between branches.

```{bash}
git checkout "mall-exp"
git checkout "main"
```

###  My Wishes to the Class Notes

I now will add my name and learn wishes to the wishlist in the class notes. I did this by opening the index.qmd file and adding my name alphabetically to the list. When I saved the file, I checked the running html link in local host on my browser to see my changes. The changes were found succesfully on http://localhost:4048/.
